"""Add mode to projects

Revision ID: d9e626f2d8ac
Revises: 1a1069715f9b
Create Date: 2026-03-08 01:15:05.814061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e626f2d8ac'
down_revision: Union[str, Sequence[str], None] = '1a1069715f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('mode', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'mode')
    # ### end Alembic commands ###
